---
- name: Converge
  hosts: molecule-test
  gather_facts: false
  vars:
    credentials_show_argocd: true
    credentials_show_keycloak: true
    credentials_show_openbao: false
    credentials_verbose: false
  tasks:
    - name: Import credentials role
      import_role:
        name: credentials