apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kcp-routing
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  project: control-plane
  source:
    repoURL: file:///repo
    targetRevision: HEAD
    path: control-plane/gitops/argocd/main/apps/infrastructure/kcp-routing
  destination:
    server: https://kubernetes.default.svc
    namespace: kcp
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
