apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage-secrets
  namespace: backstage
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore

  target:
    name: backstage-secrets
    creationPolicy: Owner

  data:
    - secretKey: KEYCLOAK_BACKSTAGE_CLIENT_SECRET
      remoteRef:
        key: backstage
        property: keycloak_client_secret

    - secretKey: ARGOCD_API_TOKEN
      remoteRef:
        key: backstage
        property: argocd_api_token

    - secretKey: ARGOCD_AUTH_HEADER
      remoteRef:
        key: backstage
        property: argocd_auth_header

    - secretKey: KEYCLOAK_SYNC_USERNAME
      remoteRef:
        key: keycloak/backstage-sync
        property: username

    - secretKey: KEYCLOAK_SYNC_PASSWORD
      remoteRef:
        key: keycloak/backstage-sync
        property: password
