apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cluster-kcp-root
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: cluster-kcp-root
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        labels:
          argocd.argoproj.io/secret-type: cluster
      data:
        name: kcp-root
        server: "https://kcp.kcp.svc.cluster.local:6443/clusters/root"
        config: "{{ .config }}"
  data:
  - secretKey: config
    remoteRef:
      key: kcp/root-kubeconfig
      property: config
