apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-lockdown
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "9"
    argocd/app-name: argocd-lockdown
spec:
  project: control-plane
  source:
    repoURL: file:///repo
    targetRevision: HEAD
    path: control-plane/gitops/argocd/main/apps/argocd-lockdown
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
