apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kcp-keycloak-oidc-ca
  namespace: kcp
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kcp-keycloak-oidc-ca
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: keycloak/oidc-ca
        property: ca_crt
