apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kcp-api-syncagent-agencies
  annotations:
    argocd.argoproj.io/sync-wave: "2"
rules:
  - apiGroups:
      - euro.scale
    resources:
      - agencystacks
      - agencystacks/status
      - customerstacks
      - customerstacks/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kcp-api-syncagent-agencies
  annotations:
    argocd.argoproj.io/sync-wave: "2"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kcp-api-syncagent-agencies
subjects:
  - kind: ServiceAccount
    name: kcp-api-syncagent
    namespace: kcp
