apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: kcp-api-syncagent
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  providerConfigRef:
    name: helm-provider
  rollbackLimit: 3
  forProvider:
    namespace: kcp
    skipCreateNamespace: true
    chart:
      name: api-syncagent
      repository: https://kcp-dev.github.io/helm-charts
    values:
      apiExportEndpointSliceName: agencies.euro.scale
      agentName: control-plane
      kcpKubeconfig: kcp-syncagent-kubeconfig
