apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kcp-syncagent-kubeconfig
  namespace: kcp
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: kcp-syncagent-kubeconfig
    creationPolicy: Owner
  data:
    - secretKey: kubeconfig
      remoteRef:
        key: kcp/syncagent-agencies-kubeconfig
        property: kubeconfig_b64
        decodingStrategy: Base64
