apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-mtls
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: control-plane
  source:
    repoURL: file:///repo
    targetRevision: HEAD
    path: control-plane/gitops/argocd/bootstrap/apps/infrastructure/istio-mtls
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 20
      backoff:
        duration: 20s
        factor: 2
        maxDuration: 5m
    syncOptions:
      - CreateNamespace=true
