---
credentials_show_argocd: true
credentials_show_keycloak: true
credentials_show_openbao: true
credentials_verbose: true

keycloak_admin_secret_name: "keycloak-admin-credentials"
keycloak_namespace: "keycloak"
openbao_secret_name: "openbao-root-token"
openbao_namespace: "openbao"