---
certs_ensure_keycloak_oidc: true
certs_apply_to_k8s: true
certs_organization: Euroscale

keycloak_host: keycloak.internal.euroscale.local
keycloak_namespace: keycloak

keycloak_oidc_ca_key: "{{ certs_output_dir }}/keycloak-oidc-ca.key"
keycloak_oidc_ca_crt: "{{ certs_output_dir }}/keycloak-oidc-ca.crt"
keycloak_oidc_ca_csr: "{{ certs_output_dir }}/keycloak-oidc-ca.csr"
keycloak_oidc_tls_key: "{{ certs_output_dir }}/keycloak-oidc-tls.key"
keycloak_oidc_tls_crt: "{{ certs_output_dir }}/keycloak-oidc-tls.crt"
keycloak_oidc_tls_csr: "{{ certs_output_dir }}/keycloak-oidc-tls.csr"

certs_output_dir: "{{ playbook_dir }}/../../gitops/argocd/bootstrap/apps/identity-management/keycloak-resources/certs"